---
- name: Check if paren already exists
  ansible.builtin.stat:
    path: '{{ mkprivdir__parent_dir }}'
  register: parent

- name: Create directory parent
  ansible.builtin.file:
    state: directory
    path: '{{ mkprivdir__parent_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: not parent.stat.exists

- name: Create directory
  ansible.builtin.file:
    state: directory
    path: '{{ mkprivdir__dir }}'
    owner: '{{ mkprivdir__user }}'
    group: '{{ mkprivdir__group }}'
    mode: '{{ mkprivdir__mode }}'
